In [1]:
import numpy as np

In [2]:
#creating an empty vector using numpy
zero_vector = np.zeros(5)

In [3]:
#creating an two-dimensional array (matrix)
#while creating a touple, it takes two arguments. One saying the number of rows and the second with the number of collumns
zero_matrix = np.zeros((5,3))


In [4]:
zero_vector

array([0., 0., 0., 0., 0.])

In [5]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#in this case, lower case variables are vectors and upper case are matrix (2-dimensional arrays)
x = np.array([1,2,3])
y = np.array([2,4,6])

In [7]:
#when constructing a matrix, u specify the elements of each row as a list
[[1,3],[5,9]]

[[1, 3], [5, 9]]

In [9]:
A= np.array([[1,3],[5,9]])

In [10]:
A

array([[1, 3],
       [5, 9]])

In [14]:
#to take the transpose of the matrix, the first row becomes the first collumn and vice-versa
A.transpose()

array([[1, 5],
       [3, 9]])

In [15]:
#numpy array's length may not be modified after being created!!!

In [ ]:
#slicing and numpy array

In [17]:
a = np.array([1,2,3])
b = np.array([2,4,6])
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[2,4,6],[8,10,12]])

In [18]:
#access the 3rd element of the array x
x[2]

3

In [19]:
#slicing
x[0:2]

array([1, 2])

In [20]:
z = x+y

In [21]:
z

array([3, 6, 9])

In [ ]:
#note that this sums the 1st element of array x to the 1st element of array y and so on.

In [23]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#gives me the access to the second collumn of the X array 
X[:,1]

array([2, 5])

In [25]:
Y[:,1]

array([ 4, 10])

In [26]:
#added the 2 2nd collumns of X and Y arrays
X[:,1]+Y[:,1]

array([ 6, 15])

In [27]:
#Access to the second row of the X array
X[1,:]

array([4, 5, 6])

In [28]:
#adding the second rows of both arrays
X[1,:]+ Y[1,:]

array([12, 15, 18])

In [29]:
#gives the same exact value of X[1,:] ( the second row )
X[1]

array([4, 5, 6])

In [30]:
#putting a plus sign on lists concatenates those lists, but not sums
[2,4]+[5,6]

[2, 4, 5, 6]

In [32]:
#turning into numpy arrays, + sign will sum the elements instead of concatenate
np.array([2,4])+np.array([5,6])

array([ 7, 10])

In [33]:
#example
#note that [1:2] takes a list of the 2nd element [1] until the 3rd element[2], NOT INCLUDING it
n = np.array([1,2,5])
n[1:2]

array([2])

In [34]:
#another example
#this takes an error because t has 2 elements and u has 3 elements, they have different shapes.
t = np.array([1,2])
u = np.array([3,4,5])
t + u

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [35]:
#INDEXING NUMPY ARRAYS

In [36]:
z1 = np.array([1,3,5,7,9])
z2 = z1 + 1

In [37]:
z1

array([1, 3, 5, 7, 9])

In [38]:
z2

array([ 2,  4,  6,  8, 10])

In [42]:
ind = np.array([0,2,3])

In [43]:
z1[ind]

array([1, 5, 7])

In [44]:
#creating boolean arrays using logical operators
z1>6

array([False, False, False,  True,  True])

In [45]:
#using boolean arrays to index
#note that it takes the values that are True by the index
z1[z1 > 6]

array([7, 9])

In [46]:
z2[z1 > 6]

array([ 8, 10])

In [47]:
ind = z1 > 6

In [48]:
ind

array([False, False, False,  True,  True])

In [49]:
z1[ind]

array([7, 9])

In [50]:
z2[ind]

array([ 8, 10])

In [ ]:
#IMPORTANT
#If I modify an array that came from another array, that changes both, so it's not a copy, it's a view (slices)!

In [51]:
z1 = np.array([1,3,5,7,9])

In [52]:
w = z1[0:3]

In [53]:
w

array([1, 3, 5])

In [54]:
#modifying the 1st element of w array
w[0] = 3

In [55]:
#modified
w

array([3, 3, 5])

In [56]:
#the corresponding element modified on w on z1 is also modified
z1

array([3, 3, 5, 7, 9])

In [57]:
#doing the exact same thing but indexing
z1 = np.array([1,3,5,7,9])

In [58]:
ind = np.array([0,1,2])

In [59]:
z1

array([1, 3, 5, 7, 9])

In [60]:
ind

array([0, 1, 2])

In [61]:
w = z1[ind]

In [62]:
w

array([1, 3, 5])

In [63]:
#now I changed the 1st element of w
w[0] = 3

In [64]:
#modified
w

array([3, 3, 5])

In [65]:
#but z1's 1st element is not modified like on slicing, when I index, it makes a copy!
z1

array([1, 3, 5, 7, 9])

In [66]:
#examples
#when I use the another array as an index, it works!
a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

In [67]:
#the "is" comparison operator tests if two objects are the same exact object, not if they have the same exact values!
c = b[1:]
b[a] is c

False

In [68]:
#constructing an array of 10 linear spaces between 1 to 100 
#the 1st argument is the start, the second is the stop (which will bi included) and the third is the number of points that
#I'd like to have in my array
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [69]:
#now I'll construct an array of 10 logarithmically space elements between 10 and 100
#NOW BE CAREFUL
#THE FIRST element is the LOG of the element I'd like to start
#in this case I'd like to start with 10, so I input the log of 10 (which is 1)
#THE SECOND element is the endpoint in the array
#in this case I'd like to end in 100, so I have to input the log of 100 (which is 2)
#THE THIRD element(as before) is the number of elements in our array.
np.logspace(1, 2, 10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [70]:
#note that the first element is 10, which is the start, the last element is 100, which is the endpoint and the
#another elements are uniformly spaced between those two extreme points in the LOGARITHIMIC space

In [71]:
#now I'll construct an array of ten logarithmically spaced elements between  250 and 500
#at first I'd have to get the log10 of 250 and 500
np.logspace(np.log10(250), np.log10(500), 10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [72]:
#now I'll check the shape and the size of an array
X = np.array([[1,2,3],[4,5,6]])

In [73]:
#that shows me that X array have 2 rows and 3 collumns
X.shape

(2, 3)

In [74]:
#that shows me that X has 6 elements on the array
X.size

6

In [75]:
#note that I didn't had to use () or size on the above examples
#this is because SHAPE and SIZE are DATA ATRIBUTES of the array, not METHODS!!!

In [76]:
#now I'll check if the elements of some array fulfills some logical conditions
#in the example I'll check: 
#first if any of the elements of a given array are greater than 0.9
#second if all the elements are or equal to 0.1
x  = np.random.random(10)

In [77]:
np.any(x > 0.9)

False

In [78]:
np.all(x >= 0.1)

True

In [79]:
x

array([0.87272866, 0.28228086, 0.1762497 , 0.22491118, 0.70054672,
       0.61669351, 0.88916648, 0.23990514, 0.49599621, 0.38173183])

In [80]:
#checks!

In [81]:
#example
x = 20
not np.any([x%1 == 0 for i in range(2,x)])

False

In [82]:
#x%i == 0 tests if x has remainder when divided by i.
#If this is not true for all values strictly between 1 and x it must be prime! 